"""Declarative base, shared column types and mixins for every persistent entity.

Conventions (ADR-004):
- Every entity has a UUID primary key generated by the system (RN-001).
- Enumerations are stored as VARCHAR + CHECK (``native_enum=False``) so they can evolve
  without PostgreSQL ``ALTER TYPE`` migrations and work on SQLite in unit tests.
- JSON columns use JSONB on PostgreSQL and JSON elsewhere.
- Entities with ``SoftDeleteMixin`` are never physically deleted (RN-005).
"""

import enum
import uuid
from datetime import UTC, date, datetime
from decimal import Decimal
from typing import Any, ClassVar

from sqlalchemy import JSON, DateTime, Enum, ForeignKey, MetaData, Text, Uuid
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

NAMING_CONVENTION = {
    "ix": "ix_%(table_name)s_%(column_0_N_name)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}

JsonType = JSON().with_variant(JSONB(), "postgresql")


def new_uuid() -> uuid.UUID:
    """Time-ordered UUIDv7 when available (Python 3.14+), UUIDv4 otherwise."""
    factory = getattr(uuid, "uuid7", uuid.uuid4)
    return factory()


def utcnow() -> datetime:
    return datetime.now(UTC)


def str_enum(enum_cls: type[enum.Enum], name: str) -> Enum:
    """Portable enum column: VARCHAR with a named CHECK constraint."""
    return Enum(
        enum_cls,
        name=name,
        native_enum=False,
        create_constraint=True,
        length=40,
        values_callable=lambda members: [member.value for member in members],
        validate_strings=True,
    )


def to_audit_value(value: Any) -> Any:
    """Serialize a column value into a JSON-compatible representation for the audit log."""
    if value is None or isinstance(value, bool | int | float | str):
        return value
    if isinstance(value, enum.Enum):
        return value.value
    if isinstance(value, uuid.UUID):
        return str(value)
    if isinstance(value, datetime | date):
        return value.isoformat()
    if isinstance(value, Decimal):
        return str(value)
    if isinstance(value, dict | list):
        return value
    return str(value)


class Base(DeclarativeBase):
    metadata = MetaData(naming_convention=NAMING_CONVENTION)
    type_annotation_map: ClassVar[dict[Any, Any]] = {
        dict[str, Any]: JsonType,
        list[Any]: JsonType,
        datetime: DateTime(timezone=True),
    }

    # Entities are audited field by field unless they opt out (append-only tables, audit log).
    __audited__: ClassVar[bool] = True
    # Tables whose rows can only be inserted (no UPDATE, no DELETE).
    __append_only__: ClassVar[bool] = False
    # Columns never written to the audit log (noise or secrets).
    __audit_exclude__: ClassVar[frozenset[str]] = frozenset({"created_at", "updated_at"})


class UUIDPrimaryKeyMixin:
    id: Mapped[uuid.UUID] = mapped_column(Uuid, primary_key=True, default=new_uuid)


class TimestampMixin:
    created_at: Mapped[datetime] = mapped_column(default=utcnow)
    updated_at: Mapped[datetime] = mapped_column(default=utcnow, onupdate=utcnow)


class SoftDeleteMixin:
    """Logical deletion with date, user and mandatory reason (RNF-006, RN-005)."""

    deleted_at: Mapped[datetime | None] = mapped_column(default=None, index=True)
    deleted_by_id: Mapped[uuid.UUID | None] = mapped_column(ForeignKey("app_user.id"), default=None)
    deletion_reason: Mapped[str | None] = mapped_column(Text, default=None)

    @property
    def is_deleted(self) -> bool:
        return self.deleted_at is not None
